### ISSUE TITLE
doesn't work at all

### ISSUE THREAD

**Issue by cf73** [kadegray/statamic-phone-number-fieldtype#1]
Installed using composer and added to blueprint. Tried various configs. Entering a number does NOT result in it being formatted, and saving the entry does NOT save the number, which is blank in the MD file and when reloading the entry in cp.

**Comment by kadegray** [comment]
Sorry, I'm going to need more information.

What version of Statamic are you using?
Are you using control panel to edit blueprints / configs / entries?
What is the MD file you are referring to?
Were you entering a number with the country code? The automatic local formatting happens when it knows the country of the number. If you are entering the local format of the number while a different country is selected it wont format it.

**Comment by cf73** [comment]
Thanks for the response. Using the final 3.* version of Statamic before 4.0. All up to date. Using the control panel to edit blueprints/configs/entries, yes. I installed your phone number add-on using the composer cli method. The MD file = the entry in a collection where I’m trying to save the phone number. It’s a dealer store selling musical equipment, in a ‘Dealers’ collection. I see the field for the phone number just fine in the control panel when viewing this entry (i.e. adding it to the blueprint was successful), but typing numbers into the field doesn’t auto-format them in any way, and saving the entry results in the numbers being discarded, even if the blueprint is configured to ‘save even if doesn’t validate’ (I forget the exact wording). Checking the entry markdown file shows that there is no line for phone_number, even after saving. I tried setting preferred country, initial country, etc., all to US, since the dealer locations are only in the US, but nothing makes it work; I still don’t get formatting. Even allowing all countries and then choosing US manually still results in no formatting, and nothing being saved. Hoping you can shed some light… Thanks! C   From: Kade GraySent: Wednesday, May 10, 2023 7:20 PMTo: kadegray/statamic-phone-number-fieldtypeCc: cf73; AuthorSubject: Re: [kadegray/statamic-phone-number-fieldtype] doesn't work at all (Issue #1) Sorry, I'm going to need more information.What version of Statamic are you using?Are you using control panel to edit blueprints / configs / entries?What is the MD file you are referring to?Were you entering a number with the country code? The automatic local formatting happens when it knows the country of the number. If you are entering the local format of the number while a different country is selected it wont format it.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by kadegray** [comment]
Thank you for those details.

Typing numbers into the field often doesn't format them until it 'recognizes' the number and even then it may just leave it as +12071524815. I think in the docs I mention that reloading the page makes the field render the number formatted in the local format.

Just to be clear about how formatting works in this fieldtype.
- The input's formatting is only visual and convenience.
- When the phone number is saved to the entry (the md file) it will be saved in e164 format (that is: +12071234567). This is an international phone format for data consistency.
- When displaying the phone number in an antler you use modifiers that format the number how you would like. Documented here: https://github.com/kadegray/statamic-phone-number-fieldtype#modifiers

Please confirm that the experience you are getting regarding formatting is the same with the input on this page too: https://intl-tel-input.com/. If its not working the same as there then let me know.

But whether it is formatting the number in the input is not the main issue I read that you are having which is the phone_number not being saved to the entry and the number being discarded.

First question, do you have multisite enabled?

If no, please paste the phone_number field config so I can try to replicate the issue. (resources/blueprints/collections.. > your blueprint yaml > fields > the phone_number field config)

I played around with a few different configurations myself based on the information you provided and couldn't replicate the issue. I just want to rule out its something to do with the field config.

Thank you for your patience.

**Comment by cf73** [comment]
Thanks for the email.

I tried entering a number at https://intl-tel-input.com/
International Telephone Input (intl-tel-input.com) as you suggest, and the behavior is the same as in my local install — no automatic formatting happens. I entered a valid phone number, clicked outside of the input field, tried changing the country and changing it back again; nothing. It just remains as an unformatted string, e.g. 1234567890. Refreshing the page clears the field. I tried this in macOS (latest version) using MS Edge (latest version) and Safari (also latest). Same behavior each time.

Not using multisite.

Here’s the blueprint:

sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: dealer_address
        field:
          enabledFields:
            - name
            - street
            - street2
            - postCode
            - city
            - state
            - country
            - latitude
            - longitude
          defaultCountry: US
          geoCode: true
          showCoordinates: false
          display: 'Dealer Address'
          type: address
          icon: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" height="24" width="24"><g transform="matrix(2,0,0,2,0,0)"><path d="M23.25,9V4.65a1.5,1.5,0,0,0-.943-1.393l-6-2.4a1.5,1.5,0,0,0-1.114,0L8.807,3.412a1.5,1.5,0,0,1-1.114,0L1.779,1.046a.75.75,0,0,0-1.029.7V16.119a1.5,1.5,0,0,0,.943,1.393l6,2.4a1.5,1.5,0,0,0,1.114,0l2.881-1.153" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"></path><path d="M8.25 3.519L8.25 20.019" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"></path><path d="M15.75 0.75L15.75 8.25" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"></path><path d="M18.75,15.449a.375.375,0,0,1,.375.375" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"></path><path d="M18.375,15.824a.375.375,0,0,1,.375-.375" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"></path><path d="M18.75,16.2a.375.375,0,0,1-.375-.375" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"></path><path d="M19.125,15.824a.375.375,0,0,1-.375.375" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"></path><path d="M18.75,11.324a4.5,4.5,0,0,1,4.5,4.5c0,1.921-2.688,5.576-3.909,7.138a.75.75,0,0,1-1.182,0c-1.221-1.561-3.909-5.217-3.909-7.138A4.5,4.5,0,0,1,18.75,11.324Z" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"></path></g></svg>'
          listable: hidden
          instructions_position: above
      -
        handle: phone_number
        field:
          show_country_select: true
          display: 'Phone Number'
          type: phone_number
          icon: phone_number
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: true
      -
        handle: email
        field:
          input_type: text
          antlers: false
          display: Email
          type: text
          icon: text
          listable: hidden
          instructions_position: above
      -
        handle: website
        field:
          input_type: text
          antlers: false
          display: Website
          type: text
          icon: text
          listable: hidden
          instructions_position: above
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          localizable: true
      -
        handle: brands
        field:
          type: terms
          taxonomies:
            - brands
          display: Brands
          mode: select
      -
        handle: dealer_region
        field:
          type: terms
          taxonomies:
            - dealer_region
          display: 'Dealer Region'
          mode: select
          instructions_position: above
          listable: hidden
          max_items: 1
          create: true
title: Dealers


Thanks for any help in resolving this!
C

**Comment by kadegray** [comment]
I think this is down to your expectations of the input to format the number at some point while typing the number in. This is not how the input works. If you type in a e164 number, that is you start with +, it will detect the country code and set the country select. The input also permits typing a number in the local format. The input will save the number in e164 format.

Please review the bullet point list that I provided in the previous comment.

I've tested the input with the config in your blueprint and it saves as expected. NOTE: If you reload the entry after you have saved it, IF the number saved was a real number it will format the number in the input in the local format. (try 3231234578)

As I mentioned in the first comment, to display a number you use one of the modifiers.

**Comment by cf73** [comment]
Thanks for continuing to try to resolve this.

I don’t really mind much whether it formats visually or not in the CP, but the not-saving part is the blocker.

I’m going to try implementing it on an entirely different machine from scratch and see if I get different results.

Btw, I did buy this add-on but am not entirely sure if it’s ‘activated’ / ‘synced’ with my install correctly. Would this result in the saves not happening? Or are there any other general configurational things you can think of that might be playing a role here?

Best,
C

**Comment by kadegray** [comment]
No, not having a licence doesn't limit function. It only permits you to use it on a public domain.

As I mentioned before, the only thing I can think of that might explain your experience is multi-site. Do you have multi-site enabled?

**Comment by cf73** [comment]
This is the content of my sites config.. no multisite, but does anything else here have an impact?

<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Sites
    |--------------------------------------------------------------------------
    |
    | Each site should have root URL that is either relative or absolute. Sites
    | are typically used for localization (eg. English/French) but may also
    | be used for related content (eg. different franchise locations).
    |
    */

    'sites' => [

        'default' => [
            'name' => config('app.name'),
            'locale' => 'en_US',
            'url' => '/',
        ],

    ],
];

**Comment by kadegray** [comment]
Let me know how it goes on your other machine.

The last thing you could do is attempt to save the phone number. Then paste a copy of the entry here (the md file).

**Comment by cf73** [comment]
One question, as potential hacky fix… can I accept input from a simple integer field (that does save to the md file), and then use your antlers tags to get the formatting? Should be able to do that, right?

C

**Comment by kadegray** [comment]
I managed to replicate the issue with a fresh install. I apologize, it was a bad mistake on my part. I need to do some more investigation to identify how I missed this but for now a fix has been pushed (1.0.2).

Please run: `composer update kadegray/statamic-phone-number-fieldtype`

Thank you for purchasing a licence and for persisting here with this issue.

Regarding your last comment, it is true that you can use the modifiers in this addon on any e164 number. However, it would need to be a string so you would use a text fieldtype. But this phone fieldtype will start saving once you run the above command.

**Comment by cf73** [comment]
Ah excellent, many thanks! Will try tomorrow.Let me know when you discover the cause.COn May 19, 2023, at 11:56 PM, Kade Gray ***@***.***> wrote:﻿
I managed to replicate the issue with a fresh install. I apologize, it was a bad mistake on my part. I need to do some more investigation to identify how I missed this but for now a fix has been pushed (1.0.2).
Please run: composer update kadegray/statamic-phone-number-fieldtype
Thank you for purchasing a licence and for persisting here with this issue.
Regarding your last comment, it is true that you can use the modifiers in this addon on any e164 number. However, it would need to be a string so you would use a text fieldtype. But this phone fieldtype will start saving once you run the above command.

**Comment by kadegray** [comment]
@cf73 It was just that a js file was not registered with statamic. Within my development environment this was not causing errors, this is the part I need to look into and make sure doesn't happen again. But I also need to test new releases with a fresh install in future.

Going to close this issue as the bugfix has been released.
